[meta]
version = 1

[[java.apps]]
name = "console-backend"
dir = "console/backend"
enabled = true

[[typescript.apps]]
name = "console-frontend"
dir = "console/frontend"
enabled = false

[[go.apps]]
name = "core-tenant"
dir = "core/tenant"
enabled = false

[[python.apps]]
name = "core-memory"
dir = "core/memory/database"
enabled = false

[[python.apps]]
name = "core-rpa"
dir = "core/plugin/rpa"
enabled = false

[[python.apps]]
name = "core-link"
dir = "core/plugin/link"
enabled = false

[[python.apps]]
name = "core-aitools"
dir = "core/plugin/aitools"
enabled = false

[[python.apps]]
name = "core-agent"
dir = "core/agent"
enabled = false

[[python.apps]]
name = "core-knowledge"
dir = "core/knowledge"
enabled = false

[[python.apps]]
name = "core-workflow"
dir = "core/workflow"
enabled = false
